### ISSUE TITLE
RTT viewer is not printing

### ISSUE THREAD

**Issue by ghost** [JF002/nrf52-baseproject#1]
Hello,

I am trying to use this framework and all is good, build files, flash, etc. Tho only problem is that I am trying to print something with RTT of Jlink and I can't see the output print. could you help me with this?

this is my src file:

```
#include <stdbool.h>
#include <stdint.h>
#include "nrf_delay.h"
#include "bsp.h"
#include "nrf.h"
#include "system_nrf52.h"
#include "nrf_delay.h"
#include "sdk_config.h"

#define ENABLE_SWD 1

static const uint8_t leds_list[LEDS_NUMBER] = { 9, 7, LED_3, LED_4 };

int main(void)
{
    /* Configure LED-pins as outputs. */
    printf("yeah nene\n");
    LEDS_CONFIGURE(LEDS_MASK);
    while (true)
    {
        for (int i = 0; i < LEDS_NUMBER; i++)
        {
            LEDS_INVERT(1 << leds_list[i]);
            printf("testing print CMAKE\n");
            nrf_delay_ms(500);
        }
    }
}
```

**Comment by JF002** [comment]
I didn't try to make RTT work with printf(), I've only tested RTT via the logging framework of NRF52-SDK.

As you can see in the file https://github.com/JF002/nrf52-baseproject/blob/master/src/main.cpp, RTT requires to be initialized (inside NRF_LOG_INIT() and  NRF_LOG_DEFAULT_BACKENDS_INIT()) and triggered via the code (NRF_LOG_PROCESS() & NRF_LOG_FLUSH()).

Maybe it's possible to use printf to sent messages to RTT, but I don't know how...

**Comment by ghost** [comment]
Thank you so much. Now is everything working. I will check on Internet how to activate the printf function. Thanks
